force-app/main/default/objects/Rating__c/Rating__c.object-meta.xml
<CustomObject>
    <label>Rating</label>
    <nameField>
        <displayFormat>Rating-{0}</displayFormat>
        <label>Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rating__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rating__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>TV Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RatingService.cls
public with sharing class RatingService {

public static void createNewRating(String stars, Id seriesId) {

    List<Rating__c> existingRating = [SELECT Id FROM Rating__c WHERE TV_Series__c=:seriesId AND CreatedById = :UserInfo.getUserId()];

    if (existingRating.size() >0) {
        existingRating[0].Score__c = stars;
        update existingRating;
    } else {
        Rating__c rating = new Rating__c(Score__c=stars, TV_Series__c=seriesId);
        insert rating;
    } 
}

    public static String checkExistingScore(Id seriesId) {
        List<Rating__c> existingRating = [SELECT Id, Score__c FROM Rating__c WHERE TV_Series__c=:seriesId AND CreatedById = :UserInfo.getUserId() LIMIT 1];
        if(existingRating.size() > 0) {
            return existingRating[0].Score__c;
        }
        return null;
    }
}