force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <label>Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Episode__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/Season_number__c.field-meta.xml
<CustomField>
    <fullName>Season_number__c</fullName>
    <label>Season number</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Season__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>TV Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SeasonTriggerHandler.cls
public with sharing class SeasonTriggerHandler {
    public static void handleSeasonBeforeDelete(Map<Id, Season__c> oldMap) {
        List<Episode__c> listOfEpisodes = [SELECT Id FROM Episode__c WHERE Season__c IN :oldMap.keySet()];
        delete listOfEpisodes;
    }

    public static void checkIfNumberIsUniqueOnInsert(List<Season__c> newList) {
        List<Decimal> listOfSesonsNumbers = new List<Decimal>();
        List<Id> listOfSeriesIds = new List<Id>();

        for (Season__c season : newList) {
            listOfSesonsNumbers.add(season.Season_number__c);
            listOfSeriesIds.add(season.TV_Series__c);
        }

        List<Season__c> existingSeasonWithSameNumberAndSeasons = [SELECT Id,Season_number__c, TV_Series__c FROM Season__c WHERE Season_number__c IN :listOfSesonsNumbers AND TV_Series__c IN :listOfSeriesIds];
        if(existingSeasonWithSameNumberAndSeasons.size() >0) {
            for(Season__c season :newList) {
                season.addError('Such Season number already exists for this Series');
            }
        }
    }

    public static void checkIfNumberIsUniqueOnUpdate(List<Season__c> newList, Map<Id, Season__c> newMap) {
        List<Decimal> listOfSesonsNumbers = new List<Decimal>();
        List<Id> listOfSeriesIds = new List<Id>();

        for (Season__c season : newList) {
            listOfSesonsNumbers.add(season.Season_number__c);
            listOfSeriesIds.add(season.TV_Series__c);
        }

        List<Season__c> existingSeasonWithSameNumberAndSeasons = [SELECT Id,Season_number__c, TV_Series__c FROM Season__c WHERE Season_number__c IN :listOfSesonsNumbers AND TV_Series__c IN :listOfSeriesIds AND Id NOT IN :newMap.keySet()];
        if(existingSeasonWithSameNumberAndSeasons.size() >0) {
            for(Season__c season :newList) {
                season.addError('Such Season number already exists for this Series');
            }
        }
    }

    public static void updateSeasonName(Map<Id, Season__c> newMap) {
        List<Season__c> listOfSeasons = [SELECT Id, Name, TV_Series__r.Name, Season_number__c FROM Season__c WHERE Id  IN :newMap.keySet()];
        for(Season__c season: listOfSeasons) {
            season.Name = season.TV_Series__r.Name + ' - ' + season.Name + ' (Season number: ' + season.Season_number__c + ')';
        }
        update listOfSeasons;
    }

}