force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <label>Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Biography</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Dance</fullName>
            </value>
            <value>
                <fullName>Disaster</fullName>
            </value>
            <value>
                <fullName>Documentary</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Epic</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>Film-Noir</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Martial Arts</fullName>
            </value>
            <value>
                <fullName>Musical</fullName>
            </value>
            <value>
                <fullName>Mystery</fullName>
            </value>
            <value>
                <fullName>Psychological</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Rom-Com</fullName>
            </value>
            <value>
                <fullName>Sci-Fi</fullName>
            </value>
            <value>
                <fullName>Short</fullName>
            </value>
            <value>
                <fullName>Sport</fullName>
            </value>
            <value>
                <fullName>Spy</fullName>
            </value>
            <value>
                <fullName>Superhero</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
            <value>
                <fullName>War</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Episode__c/fields/Episode_number__c.field-meta.xml
<CustomField>
    <fullName>Episode_number__c</fullName>
    <label>Episode number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Episode__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <inlineHelpText>Provide publicly available link to Series Avatar. Currently supported web pages are: https://cdn.pixabay.com and https://wallpapers.com/. You need to use direct image url</inlineHelpText>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Episode__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Episode__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Episode__c/recordTypes/Movie.recordType-meta.xml
<RecordType>
    <fullName>Movie</fullName>
    <active>true</active>
    <label>Movie</label>
</RecordType>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/Series_Name__c.field-meta.xml
<CustomField>
    <fullName>Series_Name__c</fullName>
    <formula>TV_Series__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Series Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Season__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>TV Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <inlineHelpText>Provide publicly available link to Series Avatar. Currently supported web pages are: https://cdn.pixabay.com and https://wallpapers.com/. You need to use direct image url</inlineHelpText>
    <label>Picture URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/fields/Series_Name__c.field-meta.xml
<CustomField>
    <fullName>Series_Name__c</fullName>
    <label>Series Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TV_Series__c/fields/Trailer_URL__c.field-meta.xml
<CustomField>
    <fullName>Trailer_URL__c</fullName>
    <label>Trailer URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PaginationController.cls
public with sharing class PaginationController {
    @AuraEnabled
    public static List<Episode__c> fetchEpisodes(Boolean buttonTypePrevious, Boolean buttonTypeNext, Integer firstEpisodeNumber, Integer lastEpisodeNumber, Integer recordsLimit, Id seasonId) {
        List<Episode__c> episodesList = new List<Episode__c>();
        if (buttonTypeNext == true) {
            // Fetch records with number greater than the lastEpisodeNumber
            episodesList = [SELECT Id, Name, Episode_number__c, Season__c FROM Episode__c WHERE Episode_number__c > :lastEpisodeNumber AND Season__c = :seasonId ORDER BY Episode_number__c ASC LIMIT :recordsLimit];
        } else if (buttonTypePrevious == true) {
            // Fetch records with number less than the firstEpisodeNumber
            episodesList = [SELECT Id, Name, Episode_number__c, Season__c FROM Episode__c WHERE Episode_number__c < :firstEpisodeNumber AND Season__c = :seasonId ORDER BY Episode_number__c DESC LIMIT :recordsLimit];
        } else {
            // Fetch the first page of records
            episodesList = [SELECT Id, Name, Episode_number__c, Season__c FROM Episode__c WHERE Season__c = :seasonId ORDER BY Episode_number__c ASC LIMIT :recordsLimit];
        }
        if (!episodesList.isEmpty()) {
            return episodesList;
        }
        return null;
    }


    @AuraEnabled(cacheable = true)
    public static Integer recordCount(Id seasonId) {
        Integer countResult = [SELECT COUNT() FROM Episode__c WHERE Season__c = :seasonId];
        System.debug('countResult => ' + countResult);
        return countResult;
    }

    @AuraEnabled
    public static List<TV_Series__c> fetchSeries(Boolean buttonTypePrevious, Boolean buttonTypeNext, Id firstId, Id lastId, Integer recordsLimit, Id seasonId) {
        List<TV_Series__c> seriesList = new List<TV_Series__c>();
        if (buttonTypeNext == true) {
            // Fetch records with number greater than the lastEpisodeNumber
            seriesList = [SELECT Id, Series_Name__c, Category__c, Description__c, Trailer_URL__c, Picture_URL__c  FROM TV_Series__c WHERE Id > :lastId ORDER BY Id ASC LIMIT :recordsLimit];
        } else if (buttonTypePrevious == true) {
            // Fetch records with number less than the firstEpisodeNumber
            seriesList = [SELECT Id, Series_Name__c, Category__c, Description__c, Trailer_URL__c, Picture_URL__c  FROM TV_Series__c WHERE Id < :firstId ORDER BY Id DESC LIMIT :recordsLimit];
        } else {
            // Fetch the first page of records
            seriesList = [SELECT Id, Series_Name__c, Category__c, Description__c, Trailer_URL__c, Picture_URL__c  FROM TV_Series__c ORDER BY Id ASC LIMIT :recordsLimit];
        }
        if (!seriesList.isEmpty()) {
            return seriesList;
        }
        return null;
    }

    @AuraEnabled(cacheable = true)
    public static Integer seriesRecordCount() {
        Integer countResult = [SELECT COUNT() FROM TV_Series__c];
        return countResult;
    }

    @AuraEnabled
    public static List<Episode__c> fetchMovies(Boolean buttonTypePrevious, Boolean buttonTypeNext, Id firstId, Id lastId, Integer recordsLimit, Id seasonId) {
        List<Episode__c> movieList = new List<Episode__c>();
        if (buttonTypeNext == true) {
            // Fetch records with number greater than the lastEpisodeNumber
            movieList = [SELECT Id, Name, Category__c, Description__c, Picture_URL__c FROM Episode__c WHERE RecordType.DeveloperName = 'Movie' AND Id > :lastId ORDER BY Id ASC LIMIT :recordsLimit];
        } else if (buttonTypePrevious == true) {
            // Fetch records with number less than the firstEpisodeNumber
            movieList = [SELECT Id, Name, Category__c, Description__c, Picture_URL__c FROM Episode__c WHERE RecordType.DeveloperName = 'Movie' AND Id < :firstId ORDER BY Id DESC LIMIT :recordsLimit];
        } else {
            // Fetch the first page of records
            movieList = [SELECT Id, Name, Category__c, Description__c, Picture_URL__c FROM Episode__c WHERE RecordType.DeveloperName = 'Movie' ORDER BY Id ASC LIMIT :recordsLimit];
        }
        if (!movieList.isEmpty()) {
            return movieList;
        }
        return null;
    }

    @AuraEnabled(cacheable = true)
    public static Integer moviesRecordCount() {
        Integer countResult = [SELECT COUNT() FROM Episode__c WHERE RecordType.DeveloperName = 'Movie' ];
        return countResult;
    }
}