force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <label>Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Episode__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>TV Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FilmListViewController.cls
public with sharing class FilmListViewController {
    @AuraEnabled
    public static List<TV_Series__c> getTVSeries() {
        return TVSeriesService.getTVSeries();
    }

    @AuraEnabled
    public static TV_Series__c getSingleTVSeries(Id tvSeriesId) {
        return TVSeriesService.getSingleTVSeries(tvSeriesId);
    }

    @AuraEnabled
    public static List<Season__c> getSeasonsPerTVSeries(Id tvSeriesId){
        return SeasonService.getSeasonsPerTVSeries(tvSeriesId);
    }
    
    @AuraEnabled
    public static List<Episode__c> getEpisodesPerSeason(Id seasonId){
        return EpisodeService.getEpisodesPerSeason(seasonId);
    }

    @AuraEnabled
    public static Episode__c getSingleEpisode(Id episodeId){
        return EpisodeService.getSingleEpisode(episodeId);
    }

    @AuraEnabled
    public static List<Episode__c> getMovies(){
        return EpisodeService.getMovies();
    }

    @AuraEnabled
    public static Episode__c getMovie(Id movieId){
        return EpisodeService.getMovie(movieId);
    }

    @AuraEnabled
    public static void createNewRating(String stars, Id seriesId){
         RatingService.createNewRating(stars, seriesId);
    }

    @AuraEnabled
    public static  List<TV_Series__c> getTopSeries(){
        return TVSeriesService.getTopRatedSeries();
    }

    @AuraEnabled
    public static String getCurrentRating(Id seriesId){
         return RatingService.checkExistingScore(seriesId);
    }
}