force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <label>Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Biography</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Dance</fullName>
            </value>
            <value>
                <fullName>Disaster</fullName>
            </value>
            <value>
                <fullName>Documentary</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Epic</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>Film-Noir</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Martial Arts</fullName>
            </value>
            <value>
                <fullName>Musical</fullName>
            </value>
            <value>
                <fullName>Mystery</fullName>
            </value>
            <value>
                <fullName>Psychological</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Rom-Com</fullName>
            </value>
            <value>
                <fullName>Sci-Fi</fullName>
            </value>
            <value>
                <fullName>Short</fullName>
            </value>
            <value>
                <fullName>Sport</fullName>
            </value>
            <value>
                <fullName>Spy</fullName>
            </value>
            <value>
                <fullName>Superhero</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
            <value>
                <fullName>War</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Episode__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <inlineHelpText>Provide publicly available link to Series Avatar. Currently supported web pages are: https://cdn.pixabay.com and https://wallpapers.com/. You need to use direct image url</inlineHelpText>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Episode__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Episode__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/Series_Name__c.field-meta.xml
<CustomField>
    <fullName>Series_Name__c</fullName>
    <formula>TV_Series__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Series Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Season__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>TV Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <inlineHelpText>Provide publicly available link to Series Avatar. Currently supported web pages are: https://cdn.pixabay.com and https://wallpapers.com/. You need to use direct image url</inlineHelpText>
    <label>Picture URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/fields/Series_Name__c.field-meta.xml
<CustomField>
    <fullName>Series_Name__c</fullName>
    <label>Series Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static TV_Series__c createSingleTVSeries(String seriesName, String seriesCategory) {
        List<TV_Series__c> listOfTVSeries = new List<TV_Series__c>();
        TV_Series__c newTVSeries = new TV_Series__c(Series_Name__c = seriesName,
        Picture_URL__c = 'https://wallpapers.com/images/high/ftestickers-black-circle-lines-scribbles-abstract-crazy-line-hd-png-download-ckk3wyb5ujs1hj5e.png',
        Category__c = seriesCategory);
        insert newTVSeries;
        return newTVSeries;
    }

    public static List<Season__c> createSeasons(Integer numOfSeasons, String seasonName, Id tvSeriesId) {
        List<Season__c> listOfSeasons = new List<Season__c>();
        for(Integer i=0;i<numOfSeasons;i++) {
            Season__c newSeason = new Season__c(Name = seasonName + i,
            TV_Series__c = tvSeriesId);
            listOfSeasons.add(newSeason);
        }
        insert listOfSeasons;
        return listOfSeasons;
        }

    public static List<Episode__c> createEpisodes(Integer numOfEpisodes, String episodeName, Id seasonId, Id tvSeriesId, String episodeDescription) {
        List<Episode__c> listOfEpisodes = new List<Episode__c>();
        for(Integer i=0;i<numOfEpisodes;i++) {
            Episode__c newEpisode = new Episode__c(Name = episodeName + i,
            Season__c = seasonId,
            TV_Series__c = tvSeriesId,
            Description__c = episodeDescription);
            listOfEpisodes.add(newEpisode);
        }
        insert listOfEpisodes;
        return listOfEpisodes;
        }
}