force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>TV Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Average Rating</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <inlineHelpText>Provide publicly available link to Series Avatar. Currently supported web pages are: https://cdn.pixabay.com and https://wallpapers.com/. You need to use direct image url</inlineHelpText>
    <label>Picture URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/fields/Trailer_URL__c.field-meta.xml
<CustomField>
    <fullName>Trailer_URL__c</fullName>
    <label>Trailer URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TVSeriesService.cls
public with sharing class TVSeriesService {
    public static List<TV_Series__c> getTVSeries() {
        return [SELECT Id, Name, Category__c, Description__c, Trailer_URL__c, Picture_URL__c, Average_Rating__c FROM TV_Series__c ORDER BY Name];
    }

    public static TV_Series__c getSingleTVSeries(Id tvSeriesId) {
        return [SELECT Id, Name, Category__c, Description__c, Trailer_URL__c,  Picture_URL__c, Average_Rating__c  FROM TV_Series__c WHERE Id = :tvSeriesId][0];
    }

    public static List<TV_Series__c> getTopRatedSeries() {
        return [SELECT Id, Name, Category__c, Description__c, Picture_URL__c,Average_Rating__c  FROM TV_Series__c WHERE Average_Rating__c != null ORDER BY Average_Rating__c DESC LIMIT 3];
    }
    
}