force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>TV Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series__c/fields/Series_Name__c.field-meta.xml
<CustomField>
    <fullName>Series_Name__c</fullName>
    <label>Series Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestTVSeriesService.cls
@isTest
private class TestTVSeriesService {

@TestSetup
static void makeData(){
    TV_Series__c newseries = TestDataFactory.createSingleTVSeries('Test Series', 'Comedy');
}

    @isTest
    private static void testGetTVSeries() {
        List<TV_Series__c> series = TVSeriesService.getTVSeries();
        Assert.areEqual(1,series.size());
    }

    @isTest
    private static void testGetSingleTVSeries() {
        TV_Series__c  series = TestDataFactory.createSingleTVSeries('Test Series 2', 'Comedy');
        TVSeriesService.getSingleTVSeries(series.Id);
        Assert.areEqual('Test Series 2',series.Series_Name__c );
    }
    
}